### ISSUE TITLE
Remove the explicit religious alignment

### ISSUE THREAD

**Issue by TheRawMeatball** [katharostech/katharos-license#1]
I've read the license, and while I can get behind most of it, the explicitly religious paragraph taking the bible as the source of "good" feels incorrect and directly contradicts with multiple clauses written underneath, especially the one which disallows discrimination based on religion. I feel that the explicit religiousness of the license is incredibly non-inclusive.

**Comment by erlend-sh** [comment]
The license is being discussed here: https://github.com/katharostech/bevy_retro/issues/1

**Comment by zicklag** [comment]
I've pushed an update to the license and the README with answers to most questions. 

I've also updated the preamble to indicate that our license terms are derived from what _we believe_ God would want us to do, and our interpretation of the Bible.

As far as removing all religious references, that is something we have decided not to do. Our beliefs are foundational to _why_ we have created the license, and us sharing that doesn't exclude anybody from any other religions or ways of thought.
