### ISSUE TITLE
The Katharos License is not an Open Source license as defined by the Open Source Definition.

### ISSUE THREAD

**Issue by striezel** [katharostech/katharos-license#5]
Currently, the decription states that The Katharos License is _"An Ethical Open Source license designed to prevent impure or destructive use of shared works."_, i. e. it should be an Open Source license. However, the [Open Source Definition](https://opensource.org/osd/) by the OSI states, among other things:

> 6. No Discrimination Against Fields of Endeavor
>
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

This is contradicted by the "Permitted Use of Work" section of The Katharos License which explicitly excludes certain fields of endeavor from using software licensed under The Katharos License. Don't get me wrong here, I can totally understand why you put those restrictions there, and I believe they are well-intended. Nevertheless, putting any such restrictions in a license makes the license **formally unfit** to meet the Open Source Definition as published by the Open Source Initiative.

So a license can be either an Open Source license or an Ethical license, where Ethical means to restrict the licensed software's use from certain use cases that are seen as unethical by the author(s) of the license, but it cannot be both.

I think that also clears up the _"The Katharos License is not an "Open Source" license in the official sense: it has not been reviewed or approved by the [Open Source Initiative](https://opensource.org/) and may or may not comply with the [Open Source Definition](https://opensource.org/docs/osd)."_ bit in the readme: In its current version 0.2.0 the license will never be approved by the OSI as an Open Source license as it violates of the Open Source Definition.

So what I am asking here is to be more straightforward and honest about the fact that The Katharos License is not an Open Source license in the usual sense of the meaning. Please remove the term "Open Source" from the description and the readme, because this is not an Open Source license.

**Comment by zicklag** [comment]
Agreed! There are fields of endeavor that we exclude in this license, and therefore this is not an Open Source license. I updated the description and the README. 👍️

**Comment by striezel** [comment]
Thank you. :)
